### ISSUE TITLE
bug: App resets back to built in version after a successful update

### ISSUE THREAD

**Issue by ehiosunbishop** [Cap-go/capacitor-updater#395] opened 2024-06-26 03:31 UTC
### Capacitor Version

```
Installed Dependencies:

  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4
  @capacitor/cli: 5.5.1
```

### Plugin Version

```
@capgo/capacitor-updater: "^6.0.32"
```

### context(s)

```md
ManualModel: true
AutoMode: false
CapgoCloud: false
OnPremise: false
```

### Platform(s)

iOS

### Current Behavior

After running  `CapacitorUpdater.set(appUpdate);` The apps gets updated with the appUpdate but reverts back to the built in version after couple of seconds. I made sure i placed `CapacitorUpdater.notifyAppReady();` in my main.ts . I am using angular.

<img width="801" alt="image" src="https://github.com/Cap-go/capacitor-updater/assets/47338132/0879e1d1-f7b4-494f-9a33-cbb72cfad6ed">

i get that warning before the apps resets to old version

### Expected Behavior

Successful update without reverting back to the built in version.

**Comment by forumwi** [comment] 2024-07-23 22:09
I have the same problem on iOS (everything works as intended on Android), but on iOS, after using `CapacitorUpdater.set`, it simply loads the old version again. Even when using `CapacitorUpdater.next` and `CapacitorUpdater.reload`, the result is the same. I have a console log at the start in both the version on the device and the new version to differentiate them, so I know that the update is not being applied.

My Code:
```javascript
CapacitorUpdater.notifyAppReady()
hideUpdateScreen() // Hide update screen after update

App.addListener('appStateChange', async (state: any) => {
  if (state.isActive) {
    const latest = await axios.post(####) // Custom Fetch logic
    if (latest.url) {
      if (latest.force) {
        showUpdateScreen()
      }
    try {
      data = await CapacitorUpdater.download({
        url: latest.url,
        version: latest.version,
      })
      await CapacitorUpdater.set({ id: data.id })
    } catch (err) {
      console.log(err)
      hideUpdateScreen()
    }
  }
})
```

### Capacitor - Version
```
Installed Dependencies:

  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0
  @capacitor/cli: 6.0.0
```

### Plugin Version
```
@capgo/capacitor-updater: "^6.0.47"
```

I would be thankful if someone could help out.

**Comment by u12206050** [comment] 2024-08-06 12:50
Not sure if it is connected, but we have now reliably been able to reproduce on ios, that after updating using capgo, everything works, even between app closing and opening. HOWEVER when restarting the ios device, it seems the builds or something is lost/reset falling back to the native version. Unfortunately it is then stuck in this state until a new version is released, indicating that capgo does actually know what the existing version is and is just not updating or using it.

**Comment by WcaleNieWolny** [comment] 2024-08-12 06:59
I cannot reproduce this error with the automatic bundle download (`autoUpdate`). I will try to use the `set` fn

**Comment by WcaleNieWolny** [comment] 2024-08-12 07:15
Cannot reproduce, closing

**Closed by WcaleNieWolny** 2024-08-12 07:15 UTC

**Comment by u12206050** [comment] 2024-08-12 12:36
After updating to @capacitor to v6 this issue seems to be resolved.

**Comment by angelLain** [comment] 2024-08-24 20:55
Same error, I tried tado but it keeps going back to default or previous version after a few seconds
